# Generated by Django 5.2.11 on 2026-03-01 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeekSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_of_week', models.DateField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_schedules', to='schedule_app.employee')),
                ('friday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule_app.dayschedule')),
                ('monday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule_app.dayschedule')),
                ('saturday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule_app.dayschedule')),
                ('sunday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule_app.dayschedule')),
                ('thursday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule_app.dayschedule')),
                ('tuesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule_app.dayschedule')),
                ('wednesday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='schedule_app.dayschedule')),
            ],
            options={
                'unique_together': {('employee', 'start_of_week')},
            },
        ),
    ]
