# Generated by Django 5.2.11 on 2026-03-01 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_project_employees'),
        ('schedule_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(blank=True, to='projects_app.project'),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='end',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dayschedule',
            name='start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fio',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_schedules', to='schedule_app.employee'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='friday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule_app.dayschedule'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='monday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule_app.dayschedule'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='saturday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule_app.dayschedule'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='sunday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule_app.dayschedule'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='thursday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule_app.dayschedule'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='tuesday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule_app.dayschedule'),
        ),
        migrations.AlterField(
            model_name='weekschedule',
            name='wednesday',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule_app.dayschedule'),
        ),
        migrations.AlterUniqueTogether(
            name='weekschedule',
            unique_together={('employee', 'start_of_week')},
        ),
    ]
