# Generated by Django 5.2.11 on 2026-03-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('USER', 'User'), ('OWNER', 'Owner')], default='USER', max_length=10),
        ),
    ]
