# Generated by Django 3.2.16 on 2026-03-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(through='projects_app.EmployeeProject', to='schedule_app.Employee'),
        ),
    ]
